version: '3'

services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/mongo_db

  postgres:
    container_name: postgres
    image: "postgres:13"
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/data/pg_db

volumes:
  mongo_data:
  pg_data:
